### ISSUE TITLE
Have you implemented this in production?

### ISSUE THREAD

**Issue by laneparton** [DymytriiLynx/gatsby-webhooks#1]
Generally interested in solving a similar problem :)

I was wondering what your use case is and how you're implementing it?

**Comment by DymytriiDev** [comment]
Hi @laneparton, thanks for reaching out—short answer is yes.

The use case was a Gatsby site with a headless CMS. We needed to trigger a rebuild on content updates via CMS webhooks, but Gatsby had no good way to listen for them directly.

So we added a webhooks.js listener (tracked by forever), and on each deploy, the pipeline would kill the old process, pull latest code, run npm install && gatsby build, then restart webhooks.js.

To avoid excessive rebuilds from rapid CMS edits, we added a delay (webhooks:36). It waits 15 seconds after the last webhook before triggering a rebuild—batching quick edits into one build. Refreshing the timer per webhook was optional, but worked well in this case.
